name: Java CI with Maven

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Репозитори татах
        uses: actions/checkout@v3

      - name: Java 11 суулгах
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Maven-ээр төсөл build хийх
        run: mvn -B clean verify

      - name: Checkstyle шалгалт
        run: mvn checkstyle:check

      - name: JaCoCo coverage шалгалт
        run: mvn jacoco:report

      - name: Coverage 100% шалгах
        run: |
          coverage=$(grep -oPm1 "(?<=<branchCoverage>)[^<]+" target/site/jacoco/jacoco.xml | tr -d '%')
          if [ "$coverage" != "100" ]; then
            echo "Branch coverage 100% биш байна: $coverage%"
            exit 1
          fi
