name: Java CI with Maven

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Репозитори татах
        uses: actions/checkout@v3

      - name: Java 17 суулгах
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Maven-ээр төсөл build хийх
        run: mvn -B clean verify

      - name: Checkstyle шалгалт
        run: mvn checkstyle:check

      - name: JaCoCo coverage шалгалт
        run: mvn jacoco:report

      - name: Coverage 100% шалгах
        run: |
          covered=$(awk '/<counter type="BRANCH">/,/<\/counter>/ { if ($0 ~ /<covered>/) { gsub(/.*<covered>|<\/covered>.*/, "", $0); print $0 } }' target/site/jacoco/jacoco.xml)
          missed=$(awk '/<counter type="BRANCH">/,/<\/counter>/ { if ($0 ~ /<missed>/) { gsub(/.*<missed>|<\/missed>.*/, "", $0); print $0 } }' target/site/jacoco/jacoco.xml)
          total=$((covered + missed))
          percent=$((100 * covered / total))
          echo "Branch coverage: $percent%"
          if [ "$percent" -ne 100 ]; then
            echo "Branch coverage 100% биш байна: ${percent}%"
            exit 1
          fi
